server:
  port: 8761

spring:
  application:
    name: discovery-service

  config:
    import: optional:configserver:http://j9e101.p.ssafy.io:8888

  cloud:
    config:
      name: discovery
      profile: default
